#logging.level.root=debug
server:
  tomcat:
    uri-encoding: UTF-8
  port: 8080
  context-path:
  #--------TCP--netty---------
boss:
  thread:
    count: 2
worker:
  thread:
    count: 2
so:
  keepalive: true
  backlog: 100
tcp:
  port: 8088


BRACELET_TABLENAME: bracelet_

# 开启日志 格式为logging.level
logging.level:
  com.sunshine.hardware: debug

spring:
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/hardware?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123

